# Generated by Django 5.2.4 on 2025-08-15 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Seat Classes',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='seats_in_row',
        ),
        migrations.AlterField(
            model_name='airplane',
            name='airplane_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplanes', to='flights.airplanetype'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='flights.city'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='flights.country'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.airline'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.airplane'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.route'),
        ),
        migrations.CreateModel(
            name='Compartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_row', models.PositiveIntegerField()),
                ('end_row', models.PositiveIntegerField()),
                ('seats_in_row', models.CharField(help_text="Enter the seat letters for this compartment, e.g., 'ABCDEF'", max_length=10)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='flights.airplane')),
                ('seat_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='flights.seatclass')),
            ],
            options={
                'ordering': ['airplane__name', 'seat_class__name'],
            },
        ),
    ]
