# Generated by Django 5.2.4 on 2025-08-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_seatclass_remove_airplane_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatclass',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
