# Generated by Django 5.2.4 on 2025-08-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_seatclass_price_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('on time', 'On Time'), ('delayed', 'Delayed'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled'), ('diverted', 'Diverted')], default='Scheduled', max_length=20),
        ),
    ]
