# Generated by Django 5.2.4 on 2025-08-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flight_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('on time', 'On Time'), ('delayed', 'Delayed'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled'), ('diverted', 'Diverted')], default='scheduled', max_length=20),
        ),
    ]
