# Generated by Django 5.2.4 on 2025-08-15 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('flights', '0003_seatclass_price_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.seatclass'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.CharField(max_length=1),
        ),
        migrations.DeleteModel(
            name='SeatClass',
        ),
    ]
