# Generated by Django 5.2.4 on 2025-08-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_ticket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='with_luggage',
            field=models.BooleanField(default=False),
        ),
    ]
